### ISSUE TITLE
Unable to get snapshot

### ISSUE THREAD

**Issue by Alexwijn** [stevenflesch/ring-to-android-tv#6]
Hello, I recently installed the service and when there is an event the notification will be send to my SHIELD TV without any issues but is unable to retrieve a snapshot.

When I use the test command it works without any issues. Anything I can do to fix this? Thanks!

**Comment by stevenflesch** [comment]
Are you able to copy/paste the log output of the service?  It should be at /var/log/ring-to-android-tv.log

That would help diagnose what's happening.

Also, did you grant permissions on the SHIELD via adb?

**Comment by Alexwijn** [comment]
Yes, I granted the permission. But the issue is not with the notification.

Here are the logs, I also added a `console.log` on the exception when subscribing.

Maybe we also need an option to disable motion notifications because the camera limitations that I read.

```
[Mon Aug 24 2020 07:13:46 GMT+0100 (British Summer Time)] Motion detected on Front Door camera.

Snapshot saved!
Sent notification successfully: Motion Detected - Motion detected at Front Door!
[Mon Aug 24 2020 07:23:26 GMT+0100 (British Summer Time)] Motion detected on Front Door camera.
Unable to get snapshot.
Error: Snapshot failed to refresh after 60 attempts
    at RingCamera.<anonymous> (/opt/ring-to-android-tv/node_modules/ring-client-api/lib/api/ring-camera.js:279:19)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/ring-to-android-tv/node_modules/ring-client-api/lib/api/ring-camera.js:5:58)

Sent notification successfully: Motion Detected - Motion detected at Front Door!
[Mon Aug 24 2020 10:21:09 GMT+0100 (British Summer Time)] Motion detected on Front Door camera.
Unable to get snapshot.
Error: Snapshot failed to refresh after 60 attempts
    at RingCamera.<anonymous> (/opt/ring-to-android-tv/node_modules/ring-client-api/lib/api/ring-camera.js:279:19)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/ring-to-android-tv/node_modules/ring-client-api/lib/api/ring-camera.js:5:58)

Sent notification successfully: Motion Detected - Motion detected at Front Door!
[Mon Aug 24 2020 10:29:13 GMT+0100 (British Summer Time)] Motion detected on Front Door camera.
Unable to get snapshot.
Error: Snapshot failed to refresh after 60 attempts
    at RingCamera.<anonymous> (/opt/ring-to-android-tv/node_modules/ring-client-api/lib/api/ring-camera.js:279:19)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/ring-to-android-tv/node_modules/ring-client-api/lib/api/ring-camera.js:5:58)

Sent notification successfully: Motion Detected - Motion detected at Front Door!
[Mon Aug 24 2020 11:59:13 GMT+0100 (British Summer Time)] Motion detected on Front Door camera.
Unable to get snapshot.
Error: Snapshot failed to refresh after 60 attempts
    at RingCamera.<anonymous> (/opt/ring-to-android-tv/node_modules/ring-client-api/lib/api/ring-camera.js:279:19)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/ring-to-android-tv/node_modules/ring-client-api/lib/api/ring-camera.js:5:58)

Sent notification successfully: Motion Detected - Motion detected at Front Door!
[Mon Aug 24 2020 12:00:06 GMT+0100 (British Summer Time)] Motion detected on Front Door camera.
Unable to get snapshot.
Error: Snapshot failed to refresh after 60 attempts
    at RingCamera.<anonymous> (/opt/ring-to-android-tv/node_modules/ring-client-api/lib/api/ring-camera.js:279:19)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/ring-to-android-tv/node_modules/ring-client-api/lib/api/ring-camera.js:5:58)

Sent notification successfully: Motion Detected - Motion detected at Front Door!
[Mon Aug 24 2020 12:01:15 GMT+0100 (British Summer Time)] Motion detected on Front Door camera.
Unable to get snapshot.
Error: Snapshot failed to refresh after 60 attempts
    at RingCamera.<anonymous> (/opt/ring-to-android-tv/node_modules/ring-client-api/lib/api/ring-camera.js:279:19)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/ring-to-android-tv/node_modules/ring-client-api/lib/api/ring-camera.js:5:58)

Sent notification successfully: Motion Detected - Motion detected at Front Door!
[Mon Aug 24 2020 12:01:20 GMT+0100 (British Summer Time)] Doorbell pressed on Front Door camera.
Unable to get snapshot.
Error: Snapshot failed to refresh after 60 attempts
    at RingCamera.<anonymous> (/opt/ring-to-android-tv/node_modules/ring-client-api/lib/api/ring-camera.js:279:19)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/ring-to-android-tv/node_modules/ring-client-api/lib/api/ring-camera.js:5:58)

Sent notification successfully: Doorbell Ring - Doorbell rung at Front Door!
```

**Comment by stevenflesch** [comment]
If this is a battery powered camera, this is likely due to a limitation in Ring's API.  If not, then I can investigate further!

**Comment by Alexwijn** [comment]
Yeah, it's the Ring 3. It's capable of running from battery, but mine is plugged into a dedicated power line.

**Comment by stevenflesch** [comment]
I updated the depdency for `ring-client-api` to v9.9.0 - this may solve the issue.  Would you mind updating and letting me know if this resolves the issue?

I found similar reports using an older version of the API, specifically here: https://github.com/dgreif/ring/issues/293

**Comment by stevenflesch** [comment]
Closed due to lack of update.  Please feel free to re-open if you were successful or wish to further troubleshoot!
